version: '2'

services:
  ca_org1:
    image: hyperledger/fabric-ca
    container_name: ca_org1
    command: sh -c 'fabric-ca-server start --config /etc/hyperledger/fabric-ca-server-config/'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca:/etc/hyperledger/fabric-ca-server-config
    ports:
      - "7054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca_org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY_FILE
      - FABRIC_CA_SERVER_TLS_CLIENTAUTHREQUIRED=false
      - FABRIC_CA_SERVER_DEBUG=true

  ca_org2:
    image: hyperledger/fabric-ca
    container_name: ca_org2
    command: sh -c 'fabric-ca-server start --config /etc/hyperledger/fabric-ca-server-config/'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca:/etc/hyperledger/fabric-ca-server-config
    ports:
      - "8054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca_org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY_FILE
      - FABRIC_CA_SERVER_TLS_CLIENTAUTHREQUIRED=false
      - FABRIC_CA_SERVER_DEBUG=true

  ca_org3:
    image: hyperledger/fabric-ca
    container_name: ca_org3
    command: sh -c 'fabric-ca-server start --config /etc/hyperledger/fabric-ca-server-config/'
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/ca:/etc/hyperledger/fabric-ca-server-config
    ports:
      - "9054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca_org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY_FILE
      - FABRIC_CA_SERVER_TLS_CLIENTAUTHREQUIRED=false
      - FABRIC_CA_SERVER_DEBUG=true
