version: '2'

services:
  orderer.example.com:
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
    ports:
      - "7050:7050"

  peer0.hospital1.example.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=peer0.hospital1.example.com:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@hospital1.example.com/msp
    ports:
      - "7051:7051"
      - "7053:7053"

  peer0.hospital2.example.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=peer0.hospital2.example.com:7051
      - CORE_PEER_LOCALMSPID=Hospital2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@hospital2.example.com/msp
    ports:
      - "8051:7051"
      - "8053:7053"

  peer0.hospital3.example.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=peer0.hospital3.example.com:7051
      - CORE_PEER_LOCALMSPID=Hospital3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@hospital3.example.com/msp
    ports:
      - "9051:7051"
      - "9053:7053"
